// src/constants/bagsBrands.js
export const bagsBrands = [
    "Adidas",
    "Antler",
    "Arc'teryx",
    "Asics",
    "Atlantis Handmade Shoes",
    "Away",
    "Bellroy",
    "Birkenstock",
    "Blundstone",
    "Briggs & Riley",
    "Burberry",
    "Calvin Klein",
    "Chanel",
    "Chaco",
    "Clarks",
    "Coach",
    "Converse",
    "Crocs",
    "Danner",
    "Delsey",
    "Derimod",
    "Desa",
    "Dior",
    "Dr. Martens",
    "Ekster",
    "Fila",
    "Fossil",
    "Greyder",
    "Guard Leather",
    "Gucci",
    "Havaianas",
    "Hermès",
    "Herschel",
    "Hotic",
    "Hunter",
    "Ipex Leather",
    "İnci",
    "JanSport",
    "Kate Spade",
    "Kayya Bags",
    "Keen",
    "Kemal Tanca",
    "Kia Ora",
    "Kinetix",
    "L.L.Bean",
    "Leatherology",
    "Lescon",
    "Little Istanbul Gifts",
    "Louis Vuitton",
    "Manu Atelier",
    "Michael Kors",
    "Misela",
    "Mono",
    "Monos",
    "New Balance",
    "Nike",
    "OluKai",
    "Osprey",
    "Patagonia",
    "Prada",
    "Puma",
    "Reebok",
    "Red Wing",
    "Rimowa",
    "Rossea",
    "SADULLAH OZKAYA - OZKAYA KUNDURA",
    "Samsonite",
    "Sanuk",
    "SMEC Fashion",
    "Smythson",
    "Sorel",
    "STL TEKNOLOJI LTD. STI.",
    "SuperStep",
    "Teva",
    "The North Face",
    "Timbuk2",
    "Tommy Hilfiger",
    "Tortuga",
    "Travelpro",
    "Trayvax",
    "Turkish Leather",
    "Tumi",
    "Under Armour",
    "Ugg",
    "Vakko",
    "Vans",
    "Vionic",
    "Wolverine",
    "Zara",
          ];
          