// src/constants/booksStationeryHobbyBrands.js
export const booksStationeryHobbyBrands = [
    "Activision Blizzard",
    "Audio-Technica",
    "Bandai",
    "Bertelsmann",
    "BIC",
    "Bilcee",
    "Bloomsbury Publishing",
    "Bose",
    "Canson",
    "Caran d’Ache",
    "Clairefontaine",
    "Daler-Rowney",
    "Derwent",
    "Destek Publishing",
    "Dogan Kitap",
    "Dream Games",
    "Electronic Arts",
    "Everest Yayinlari",
    "Faber-Castell",
    "Fender",
    "Gibson",
    "Gulfo",
    "Guven Sanat",
    "Hachette Livre",
    "HarperCollins",
    "Hasbro",
    "Iletisim",
    "KS Games",
    "Korg",
    "Lego",
    "Leuchtturm1917",
    "Liquitex",
    "Macmillan Publishers",
    "Mattel",
    "Milton Bradley",
    "Moleskine",
    "Nintendo",
    "Oakever Games",
    "Paper Mate",
    "Parker Brothers",
    "Peak Games",
    "Pearson",
    "Pegasus Yayinlari",
    "Pentel",
    "Pilot",
    "Penguin Random House",
    "Prismacolor",
    "Ravensburger",
    "RELX Group",
    "Remzi Kitabevi",
    "Revell",
    "Rhodia",
    "Roland",
    "Sakura",
    "Scholastic",
    "Seckin Publishing",
    "Sharpie",
    "Shure",
    "Simon & Schuster",
    "Sony",
    "Staedtler",
    "Steinway & Sons",
    "Strathmore",
    "Sultan Instruments",
    "Tamiya",
    "Timas Publishing Group",
    "Ubisoft",
    "Winsor & Newton",
    "Yamaha",
    "Yilmazlar Stationery",
    "Zaza Percussion",
  ];
  