// src/constants/cosmeticsBrands.js
export const cosmeticsBrands = [
   "Arifoğlu",
  "Axe",
  "Avon",
  "Beaulis",
  "Benefit Cosmetics LLC",
  "Biore",
  "Bobbi Brown",
  "Chando",
  "Clarins",
  "Clinique",
  "Coty",
  "Cyrene",
  "Deina Cosmetics",
  "Dove",
  "Elvive/Elseve/Elvital",
  "Estee Lauder",
  "Eyüp Sabri Tuncer",
  "Farmasi",
  "Flormar",
  "Garnier",
  "Gillette",
  "Golden Rose",
  "Guerlain",
  "Head & Shoulders",
  "Herbal Essences",
  "Huncalife",
  "Innisfree",
  "Johnson & Johnson",
  "Kose Corporation",
  "L’Oreal Paris",
  "Lancome",
  "L’Occitane",
  "Luv it!",
  "Lux",
  "M.A.C",
  "Maybelline New York",
  "NARS Cosmetics",
  "Natura & Co",
  "Nako Cosmetic",
  "Neutrogena",
  "Nivea",
  "Note Cosmetics",
  "Olay",
  "Old Spice",
  "Oriflame",
  "Palmolive",
  "Pantene",
  "Pastel",
  "Pechoin",
  "POLA",
  "Procter & Gamble",
  "Raen",
  "Rejoice",
  "Revlon",
  "Rexona",
  "Rosense",
  "S'he vec",
  "Schwarzkopf",
  "Shiseido",
  "SK-II",
  "So Fly Cosmetics",
  "Sofina",
  "Sulwhasoo",
  "Sunsilk",
  "The Body Shop",
  "Tresemme",
  ];
  