// src/constants/homeAndFurnitureBrands.js
export const homeAndFurnitureBrands = [
   "ABC Carpet & Home",
  "AKM Mobilya",
  "Afroza",
  "Alfemo",
  "AllModern",
  "Alpino Mobilya",
  "American Standard",
  "Anthropologie",
  "Arhaus",
  "Armis Hali",
  "Artemide",
  "AS Oda",
  "Ashley",
  "Assuva",
  "Barker and Stonehouse",
  "Bellona",
  "Bernhardt",
  "Blu Dot",
  "Boke Furniture",
  "Bosch",
  "Burrow",
  "CB2",
  "Casa",
  "Casper",
  "Castlery",
  "ClosetMaid",
  "Cox & Cox",
  "Crate & Barrel",
  "Cree",
  "Delta Faucet",
  "Design Within Reach",
  "Digtas",
  "Dogtas",
  "Duresta",
  "Edas",
  "Edloe Finch",
  "Ekol",
  "Elfa",
  "Elve Luxury",
  "Enza Home",
  "Ethan Allen",
  "Feather and Black",
  "Feit Electric",
  "Flos",
  "Fatih Kıral",
  "GE",
  "GE Lighting",
  "Grohe",
  "Henredon",
  "Hollyhock Home",
  "IKEA",
  "InFavori",
  "Iberba",
  "Industry West",
  "Istikbal",
  "Joybird",
  "Kathy Kuo Home",
  "Kastamonu Mobilya",
  "Kelebek",
  "Kervan Mobilya",
  "KitchenAid",
  "Kohler",
  "Komposan",
  "La-Z-Boy",
  "Land",
  "LG",
  "Loaf",
  "Louis Poulsen",
  "Lulu and Georgia",
  "Made.com",
  "Mazzini Furniture",
  "Merit Furniture",
  "Mitchell Gold + Bob Williams",
  "Moen",
  "Mogno",
  "Modalife",
  "Mudo",
  "Natuzzi",
  "Nectar",
  "Oak Furnitureland",
  "Okumus",
  "One Kings Lane",
  "Orix",
  "Philips",
  "Pottery Barn",
  "Prenses Mobilya",
  "Purple",
  "Ralph Lauren Home",
  "Restore",
  "RH",
  "Roche Bobois",
  "Room & Board",
  "Saatva",
  "Samsung",
  "ScS",
  "Selimoglu",
  "Serena & Lily",
  "Seref Koltuk",
  "Serta",
  "Sealy",
  "Society Social",
  "Sofology",
  "Stok",
  "Swoon",
  "Tempur-Pedic",
  "The Citizenry",
  "The Container Store",
  "Toto",
  "Tuft & Needle",
  "Viking",
  "VNN Office Furniture",
  "Voga furniture",
  "Wayfair",
  "West Elm",
  "Whirlpool",
  "Wolf",
  "Yildiz Mobilya",
  "Zebrano",
      ];
      