// src/constants/menFashionBrands.js
export const menFashionBrands = [
   "Adidas",
  "Aimé Leon Dore",
  "AllSaints",
  "Altınyıldız",
  "American Crew",
  "Armani",
  "ASICS",
  "ASOS",
  "Balenciaga",
  "Barbour",
  "Baxter of California",
  "Beymen",
  "Belstaff",
  "Berluti",
  "Biotherm Homme",
  "Bottega Veneta",
  "Breitling",
  "Buck Mason",
  "Bulgari",
  "Burberry",
  "Calvin Klein",
  "Canada Goose",
  "Cartier",
  "CeraVe",
  "Celine",
  "Champion",
  "Chanel",
  "Church's",
  "Clinique for Men",
  "Coach",
  "Colin’s",
  "Columbia",
  "Comme des Garçons",
  "Converse",
  "Creed",
  "David Yurman",
  "De Facto",
  "Derimod",
  "Desa",
  "Dior",
  "Dolce & Gabbana",
  "Dr. Martens",
  "D’s Damat",
  "Emporio Armani",
  "Everlane",
  "Fendi",
  "Fila",
  "Givenchy",
  "Graff",
  "Gucci",
  "Gülbut",
  "H&M",
  "Harry's",
  "Hanz de Fuko",
  "Harry Winston",
  "Hatemoğlu",
  "Hermès",
  "Hugo Boss",
  "J.Crew",
  "Jack Black",
  "John Lobb",
  "John Masters Organics",
  "Kiehl's",
  "Kevin Murphy",
  "Kiğılı",
  "Kinetix",
  "Koton",
  "La Roche-Posay",
  "Lab Series",
  "LC Waikiki",
  "Le Labo",
  "Les Benjamins",
  "Lescon",
  "Louis Vuitton",
  "LTB Jeans",
  "Lululemon",
  "Machka",
  "Marmot",
  "Max Mara",
  "Mavi Jeans",
  "Michael Kors",
  "Moncler",
  "Montblanc",
  "Mountain Hardwear",
  "Mudo",
  "Network",
  "New Balance",
  "Nike",
  "Omega",
  "Oliver Peoples",
  "Patagonia",
  "Patek Philippe",
  "Perry Ellis",
  "Persol",
  "Prada",
  "Puma",
  "Ralph Lauren",
  "Ramsey",
  "Ray-Ban",
  "Reebok",
  "Reuzel",
  "Rolex",
  "Russell Athletic",
  "Saint Laurent",
  "Salomon",
  "Santoni",
  "Sarar",
  "Shiseido Men",
  "Skechers",
  "Speedo",
  "Sunspel",
  "TAG Heuer",
  "The North Face",
  "The Ordinary",
  "Tiffany & Co.",
  "Todd Snyder",
  "Tom Ford",
  "Tommy Hilfiger",
  "Under Armour",
  "Uniqlo",
  "Vakko",
  "Valentino",
  "Versace",
  "Wilson",
  "Zara",
       ];
       