// src/constants/motherAndChildBrands.js
export const motherAndChildBrands = [
  "Alisa Baby",
  "ANEX",
  "Aveeno",
  "Aziz Bebe",
  "Bebegen",
  "Bugaboo",
  "Burt's Bees Baby",
  "Carter's",
  "Cemre Tekstil",
  "Chicco",
  "Civil",
  "Çınçın",
  "Cybex",
  "Defacto",
  "Dr. Brown's",
  "Ebebek",
  "Evy Baby",
  "Fisher-Price",
  "Gap",
  "Graco",
  "H&M",
  "Hasbro",
  "Huggies",
  "Johnson's",
  "King Kids",
  "Lala",
  "LC Waikiki",
  "Lego",
  "Mattel",
  "Maxi-Cosi",
  "Mini Boden",
  "Modanisa",
  "Monica+Andy",
  "Mothercare",
  "Molfix",
  "Old Navy",
  "Özk Kids Fashion",
  "Panço",
  "Pampers",
  "Penti",
  "Philips Avent",
  "Pippa & Julie",
  "Sefa Merve",
  "SebaMed",
  "Şimşek",
  "Sleepy",
  "Tommee Tippee",
  "UPPAbaby",
  "Zara",
        ];
        