import { womenFashionBrands } from "./womenFashionBrands";
import { menFashionBrands } from "./menFashionBrands";
import { motherAndChildBrands } from "./motherAndChildBrands";
import { homeAndFurnitureBrands } from "./homeAndFurnitureBrands";
import { cosmeticsBrands } from "./cosmeticsBrands";
import { bagsBrands } from "./bagsBrands";
import { electronicsBrands } from "./electronicsBrands";
import { sportsAndOutdoorBrands } from "./sportsAndOutdoorBrands";
import { booksStationeryHobbyBrands } from "./booksStationeryHobbyBrands";

export const categories = [
    {'key': 'Women', 'image': 'women.jpg'},
    {'key': 'Men', 'image': 'men.jpg'},
    {'key': 'Mother & Child', 'image': 'mother_child.jpg'},
    {'key': 'Home & Furniture', 'image': 'home_furniture.jpg'},
    {'key': 'Cosmetics', 'image': 'cosmetics.jpg'},
    {'key': 'Bags', 'image': 'bags.jpg'},
    {'key': 'Electronics', 'image': 'electronics.jpg'},
    {'key': 'Sports & Outdoor', 'image': 'sports_outdoor.jpg'},
    {'key': 'Books, Stationery & Hobby', 'image': 'books_stationery_hobby.jpg'},
  ];
  
  export const subcategoriesMap: Record<string, string[]> = {
   'Women': [
      'Clothing',
      'Footwear',
      'Accessories',
      'Underwear & Sleepwear',
      'Sportswear',
      'Swimwear',
    ],
    'Men': [
      'Clothing',
      'Footwear',
      'Sportswear',
      'Underwear & Sleepwear',
      'Accessories',
      'Swimwear',
    ],
    'Mother & Child': [
      'Baby Clothing',
      'Kids Clothing',
      'Footwear',
      'Toys & Games',
      'Baby Care',
      'Maternity',
      'Strollers & Car Seats',
      'Feeding',
      'Safety',
    ],
    'Home & Furniture': [
      'Furniture',
      'Bedding & Bath',
      'Home Decor',
      'Kitchen & Dining',
      'Bathroom',
      'Lighting',
      'Storage & Organization',
      'Textiles',
      'Appliances',
    ],
    'Cosmetics': [
      'Skincare',
      'Makeup',
      'Haircare',
      'Fragrances',
      'Personal Care',
      'Nail Care',
      'Body Care',
    ],
    'Bags': [
      'Handbags',
      'Backpacks',
      'Tote Bags',
      'Crossbody Bags',
      'Clutches',
      'Wallets',
      'Luggage',
      'Sport Bags',
    ],
    'Electronics': [
      'Smartphones & Accessories',
      'Laptops & Computers',
      'Tablets & E-Readers',
      'Audio & Headphones',
      'Cameras & Photography',
      'Televisions & Video',
      'Smart Home Devices',
      'Wearable Technology',
      'Gaming Consoles & Accessories',
      'Home Appliances',
      'Personal Care Appliances',
    ],
    'Sports & Outdoor': [
      'Exercise & Fitness',
      'Camping & Hiking',
      'Cycling',
      'Team Sports',
      'Outdoor Recreation',   
      
    ],
    'Books, Stationery & Hobby': [
      'Books',
      'Stationery',
      'Art & Craft Supplies',
      'Hobby Kits',
      'Games & Puzzles',
      'Music & Instruments',
    ],
  };
  
  export const subSubcategoriesMap: Record<string, Record<string, string[]>> = {
    'Women': {
        'Clothing': [
          'Dresses',
          'Shirts',
          'T-Shirts',
          'Sweatshirts',
          'Pants',
          'Cardigans',
          'Coats',
          'Jeans',
          'Skirts',
          'Blouses',
          'Sweaters',
          'Jackets',
          'Trench Coats',
        ],
        'Footwear': [
          'Sneakers',        
          'Sandals',
          'Casual Shoes',
          'Heels',
          'Babette',        
          'Slippers',         
          'Boots',
          'Knee-High Boots',        
          'Loafers',
        ],
        'Accessories': [
          'Watches',
          'Belts',
          'Jewelry', 
          'Scarves',
          'Gloves',       
          'Wallets',
          'Sunglasses',
        ],
        'Underwear & Sleepwear': [
          'Bras',
          'Panties',
          'Sleepwear',        
          'Socks',
          'Undershirts & Body',
          'Corsets',
          'Bustiers',
          'Bralettes',
        ],
        'Sportswear': [
          'Sports Tops',
          'Leggings',
          'Sports Bras',
          'Shorts',
          'Tracksuits',
          'Sportswear Sets',
        ],
        'Swimwear': [
          'Bikinis',
          'One-Piece Swimsuits',
          'Cover-Ups',
        ],
      },
      'Men': {
        'Clothing': [
          'T-Shirts',
          'Shirts',
          'Pants',
          'Jeans',        
          'Shorts',
          'Sweatshirts',
          'Sweaters',
          'Jackets',
          'Suits',
          'Coats',
          'Cardigans',
          'Waistcoats',
          'Trench Coats',
        ],
        'Footwear': [
          'Sneakers',
          'Casual Shoes',
          'Boots',
          'Sandals',        
          'Formal Shoes',
          'Cleats',
          'Loafers',
          'Slippers',
          ],  
        'Accessories': [
          'Watches',
          'Belts',
          'Jewelry', 
          'Scarves',
          'Gloves',       
          'Wallets',
          'Sunglasses',
          'Ties',
        ],    
        'Underwear & Sleepwear': [
          'Boxers',        
          'Sleepwear',
          'Socks',
          'Undershirts',
        ],
        'Sportswear': [
          'Sports T-Shirts',
          'Shorts',
          'Tracksuits',
          'Sports Jackets',
          'Sportswear Sets',
        ],      
        'Swimwear': [
          'Swim Shorts',        
        ],
      },
      'Mother & Child': {
        'Baby Clothing': [
          'Bodysuits',
          'Rompers',
          'Sets',
          'Sleepwear',
          'Socks',
        ],
        'Kids Clothing': [
          'T-Shirts',
          'Pants',
          'Dresses',
          'Sweatshirts',
          'Jackets',
        ],
        'Footwear': [
          'Sneakers',
          'Sandals',
          'Boots',
          'School Shoes',
          'Sports Shoes',
          'Rain Boots',
          'Slippers',
          'Dress Shoes',
        ],
        'Toys & Games': [
          'Educational Toys',
          'Plush Toys',
          'Building Sets',
          'Dolls',
          'Puzzles',
        ],
        'Baby Care': [
          'Diapers',
          'Wipes',
          'Skincare',
          'Bathing',
          'Health',
        ],
        'Maternity': [
          'Maternity Clothing',
          'Nursing Bras',
          'Maternity Accessories',
        ],
        'Strollers & Car Seats': [
          'Strollers',
          'Car Seats',
          'Travel Systems',
        ],
        'Feeding': [
          'Bottles',
          'Breast Pumps',
          'Pacifiers',
          'High Chairs',
        ],
        'Safety': [
          'Monitors',
          'Safety Gates',
          'Outlet Covers',
        ],
      },
      'Home & Furniture': {
        'Furniture': [
          'Sofas',
          'Beds',
          'Tables',
          'Chairs',
          'Wardrobes',
        ],
        'Bedding & Bath': [
          'Bed Sheets',
          'Pillows',
          'Towels',
          'Blankets',
          'Bath Mats',
        ],
        'Home Decor': [
          'Wall Art',
          'Mirrors',
          'Candles',
          'Vases',
          'Clocks',
  
        ],
        'Kitchen & Dining': [
          'Cookware',
          'Utensils',
          'Dinnerware',        
          'Storage',
          'Plates',
          'Bowls',
          'Cups',
          'Mugs',
          'Tumblers',       
          
        ],
        'Bathroom': [
          'Shower Curtains',
          'Accessories',
          'Storage',
          'Mirrors',
        ],
        'Lighting': [
          'Lamps',
          'Ceiling Lights',
          'Wall Lights',
          'String Lights',
        ],
        'Storage & Organization': [
          'Shelves',
          'Boxes',
          'Baskets',
          'Hangers',
        ],
        'Textiles': [
          'Curtains',
          'Rugs',
          'Cushions',
          'Throws',
        ],      
      },
      'Cosmetics': {
        'Skincare': [
          'Cleansers',
          'Moisturizers',
          'Serums',
          'Masks',
          'Sunscreen',
          'Toners',
          'Eye Creams',
          'Face Oils',
          'Exfoliators',
          'Acne Treatments',
          'Anti-Aging Products',
          'Face Mists',
        ],
        'Makeup': [
          'Foundation',
          'Lipstick',
          'Eyeshadow',
          'Mascara',
          'Blush',
          'Concealer',
          'Bronzer',
          'Highlighter',
          'Eyeliner',
          'Lip Gloss',
          'Setting Spray',
          'Makeup Brushes',
        ],
        'Haircare': [
          'Shampoo',
          'Conditioner',
          'Hair Masks',
          'Styling Products',
          'Hair Tools',        
        ],
        'Fragrances': [
          'Perfumes',
          'Body Sprays',
          'Deodorants',        
        ],
        'Personal Care': [
          'Body Wash',
          'Lotions',
          'Oral Care',
          'Shaving',
          'Deodorants',
          'Hand Sanitizers',
          'Feminine Care',
          'Men\'s Grooming',
          'Bath Salts',
          'Body Scrubs',
          'Body Oils',
                ],
        'Nail Care': [
          'Nail Polish',
          'Nail Tools',
          'Nail Treatments',
          'Nail Art',
          'Nail Strengtheners',
          'Cuticle Care',
          'Nail Files',
          'Nail Clippers',
          'Nail Glue',
          'Nail Stickers',
        ],
        'Body Care': [
          'Body Scrubs',
          'Body Oils',
          'Hand Creams',
          'Foot Creams',
          'Body Butter',
          'Massage Oils',
          'Body Wash',
          'Body Lotion',
          'Body Mist',
          'Hand Sanitizer',
          'Body Sprays',        
        ],
      },
      'Bags': {
        'Handbags': [
          'Evening Bags',
          'Shoulder Bags',
          'Satchels',
          'Hobo Bags',
          'Tote Bags',
        ],
        'Backpacks': [
          'Casual Backpacks',
          'Travel Backpacks',
          'School Backpacks',
          'Laptop Backpacks',
          'Hiking Backpacks',
        ],
        'Tote Bags': [
          'Canvas Totes',
          'Leather Totes',
          'Shopping Totes',
          'Beach Totes',
        ],
        'Crossbody Bags': [
          'Messenger Bags',
          'Sling Bags',
          'Waist Bags',
          'Belt Bags',
        ],   
        'Clutches': [
          'Evening Clutches',
          'Wristlet Clutches',
          'Envelope Clutches',
          'Box Clutches',
        ],   
        'Luggage': [
          'Suitcases',
          'Travel Bags',
          'Luggage Sets',
          'Duffel Bags',
          'Carry-On Bags',
        ],
        'Sport Bags': [
          'Gym Bags',
          'Duffel Bags',
          'Sports Backpacks',
          'Equipment Bags',
          'Swim Bags',
          'Tennis Bags',
          'Golf Bags',
          'Yoga Bags',
        ],
      },
      'Electronics': {
        'Smartphones & Accessories': [
          'Smartphones',
          'Cases',
          'Chargers',
          'Screen Protectors',        
        ],
        'Laptops & Computers': [
          'Laptops',
          'Desktops',
          'Monitors',
          'Keyboards',
          'Mice',
          'SSDs',
          'HDDs',
          'RAM',
          'Graphics Cards',
          'Motherboards',
          'Processors',
          'Power Supplies',
          'Cooling Systems',
          'Computer Cases',
          'External Storage',
          'Networking Equipment',
          'Printers & Scanners',
          'Mouse Pads',        
                ],
  
        'Tablets & E-Readers': [
          'Tablets',
          'E-Readers',
          'Tablet Accessories',        
        ],
        'Audio & Headphones': [
          'Headphones',
          'Earbuds',
          'Speakers',
          'Microphones',
          'Headphones Accessories',
          'Headphones Cases',
                ],
        'Cameras & Photography': [
          'Digital Cameras',
          'DSLR Cameras',
          'Lenses',
          'Tripods',
          'Camera Bags',
          'Memory Cards',
          'Camera Filters',
          'Lighting Equipment',
          'Camera Straps',
          'Remote Shutters',
          'Camera Cleaning Kits',
          'Camera Batteries',        
          'Camera Accessories',        
        ],
        'Televisions & Video': [
          'LED TVs',
          'OLED TVs',
          'QLED TVs',
          'Smart TVs',
          'Projectors',
          'Streaming Devices',
          'TV Mounts',
          'Soundbars',
          'TV Cables',
          'Remote Controls',
          'TV Antennas',        
          'HDMI Cables',
          'TV Cleaners',
        ],
        'Smart Home Devices': [
          'Smart Lights',
          'Smart Plugs',
          'Security Cameras',
          'Smart Speakers',        
        ],
        'Wearable Technology': [
          'Smartwatches',
          'Fitness Trackers',
          'Smart Glasses',        
        ],
        'Gaming Consoles & Accessories': [
          'Consoles',
          'Controllers',
          'Games',
          'VR Headsets',        
        ],
        'Home Appliances': [
          'Refrigerators',
          'Ovens',
          'Microwaves',
          'Dishwashers',
          'Washing Machines',
          'Dryers',
          'Vacuum Cleaners',
          'Air Conditioners',
          'Freezers',
          'Combi Boilers',
          'Kettles',
          'Coffee Makers',
          'Blenders',
          'Food Processors',
          'Toasters',
          'Electric Kettles',
          'Rice Cookers',
          'Air Fryers',
          'Slow Cookers',
          'Stand Mixers',
          'Juicers',
          'Irons',
          'Fans',
          'Dehumidifiers',
          'Air Purifiers',
        ],
        'Personal Care Appliances': [
          'Hair Dryers',
          'Hair Straighteners',
          'Hair Curlers',
          'Hair Clippers',
          'Hair Brushes',
          'Weighing Scales',
          'Massagers', 
          'Shaving Machines',        
        ],
      },
      'Sports & Outdoor': {
        'Exercise & Fitness': [
          'Yoga Mats',
          'Dumbbells',
          'Resistance Bands',
          'Treadmills',
          'Elliptical Machines',
          'Rowing Machines',
          'Stationary Bikes',
          'Strength Training Equipment',        
          'Fitness Accessories',
          'Fitness Equipment',
        ],
        'Camping & Hiking': [
          'Tents',
          'Sleeping Bags',
          'Backpacks',
          'Camping Stoves',
          'Camping Chairs',
          'Camping Tables',
          'Camping Accessories',
          'Camping Cookware',
          'Camping Utensils',
          'Camping Storage',
          'Camping Accessories',        
        ],
        'Cycling': [
          'Bicycles',
          'Helmets',
          'Cycling Gear',
          'Accessories',
          'Cycling Clothing',
          'Cycling Shoes',        
        ],
        'Team Sports': [
          'Soccer Balls',
          'Basketballs',
          'Volleyballs',
          'Jerseys',        
        ],
        'Outdoor Recreation': [
          'Fishing Gear',
          'Kayaks',
          'Skateboards',
          'Scooters',
          'Water Sports',
                ],        
      },
      'Books, Stationery & Hobby': {
        'Books': [
          'Fiction',
          'Non-Fiction',
          'Children\'s Books',
          'Educational',
        ],
        'Stationery': [
          'Pens',
          'Notebooks',
          'Planners',
          'Sticky Notes',
        ],
        'Art & Craft Supplies': [
          'Paints',
          'Brushes',
          'Sketchbooks',
          'Craft Kits',
                ],
        'Hobby Kits': [
          'Model Kits',
          'Knitting',
          'Sewing',
          'DIY Projects',        
        ],
        'Games & Puzzles': [
          'Board Games',
          'Puzzles',
          'Card Games',
          'Chess',      ],
        'Music & Instruments': [
          'Guitars',
          'Keyboards',
          'Accessories',
          'Sheet Music',        
        ],
      },
  };
  
  export const jewelryTypes = [  'Necklace',
    'Earring',
    'Piercing',
    'Ring',
    'Bracelet',
    'Anklet',
    'NoseRing',
    'Set', ];
  export const jewelryMaterials = [ 'Iron',
    'Steel',
    'Gold',
    'Silver',
    'Diamond',
    'Copper', ];
  export const pantSizesByCategory = {
    Women: [ 'XXS / 32',
    'XS / 34',
    'S / 36',
    'M / 38',
    'L / 40',
    'XL / 42',
    'XXL / 44',
    'XXXL / 46',
    '4XL / 48',
    '5XL / 50',
    '24',
    '6XL / 52',
    '25',
    '7XL / 54',
    '26',
    '8XL / 56',
    '27',
    '9XL / 58',
    '28',
    '10XL / 60',
    '29',
    '30',
    '31',
    '32',
    '33' ],
    Men:    [ 'L',
    'L/XL',
    'XL',
    'XXL',
    '2XL',
    '3XL',
    '4XL',
    '5XL',
    '6XL',
    '7XL',
    '29',
    '30',
    '31',
    '32',
    '33',
    '34',
    '36',
    '38',
    '40',
    '42',
    '44',
    '46',
    '48',
    '50',
    '52',
    '54',
    '56',
    '58',
    'XXXL',
    '8XL',
    'XS',
    'S',
    'S/M',
    'M' ],
  };
  export const clothingSizes = [ 'XXS',
    'XS',
    'S',
    'M',
    'L',
    'XL',
    'XXL',
    '3XL',
    '4XL', ];
  export const clothingFits  = [ 'Slim',
    'Regular',
    'Loose',
    'Oversized', ];
  export const clothingTypes = [ 'Cotton',
    'Polyester',
    'Wool',
    'Silk',
    'Denim',
    'Leather',
    'Linen',
    'Nylon', ];
  export const footwearSizesByCategory = {
    Women: [  '35',
        '36',
        '37',
        '38',
        '39',
        '40',
        '41',
        '42',
        '43'],
    Men:   [ '39',
    '40',
    '41',
    '42',
    '43',
    '44',
    '45',
    '46',
    '47',
    '48' ],
    Kids:  [  '28',
        '29',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36'],
  };
 
export const colorOptions = [
  { name: 'Blue',        hex: '#0000FF' },
  { name: 'Orange',      hex: '#FFA500' },
  { name: 'Yellow',      hex: '#FFFF00' },
  { name: 'Black',       hex: '#000000' },
  { name: 'Brown',       hex: '#A52A2A' },
  { name: 'Dark Blue',   hex: '#00008B' },
  { name: 'Gray',        hex: '#808080' },
  { name: 'Pink',        hex: '#FFC0CB' },
  { name: 'Red',         hex: '#FF0000' },
  { name: 'White',       hex: '#FFFFFF' },
  { name: 'Green',       hex: '#008000' },
  { name: 'Purple',      hex: '#800080' },
  { name: 'Teal',        hex: '#008080' },
  { name: 'Lime',        hex: '#00FF00' },
  { name: 'Cyan',        hex: '#00FFFF' },
  { name: 'Magenta',     hex: '#FF00FF' },
  { name: 'Indigo',      hex: '#4B0082' },
  { name: 'Amber',       hex: '#FFBF00' },
  { name: 'Deep Orange', hex: '#FF5722' },
  { name: 'Light Blue',  hex: '#ADD8E6' },
  { name: 'Deep Purple', hex: '#673AB7' },
  { name: 'Light Green', hex: '#90EE90' },
  { name: 'Dark Gray',   hex: '#A9A9A9' },
  { name: 'Beige',       hex: '#F5F5DC' },
  { name: 'Turquoise',   hex: '#40E0D0' },
  { name: 'Violet',      hex: '#EE82EE' },
  { name: 'Olive',       hex: '#808000' },
  { name: 'Maroon',      hex: '#800000' },
  { name: 'Navy',        hex: '#000080' },
  { name: 'Silver',      hex: '#C0C0C0' },
];

export const brandsByCategory: Record<string, Record<string, string[]>> = {   
    Women: {
      'Clothing': womenFashionBrands,
      'Footwear': womenFashionBrands,
      'Accessories': womenFashionBrands,
      'Underwear & Sleepwear': womenFashionBrands,
      'Sportswear': womenFashionBrands,
      'Swimwear': womenFashionBrands,
    },
    Men: {
      'Clothing': menFashionBrands,
      'Footwear': menFashionBrands,
      'Sportswear': menFashionBrands,
      'Underwear & Sleepwear': menFashionBrands,
      'Accessories': menFashionBrands,
      'Swimwear': menFashionBrands,
    },
    'Mother & Child': {
      'Baby Clothing': motherAndChildBrands,
      'Kids Clothing': motherAndChildBrands,
      'Footwear': motherAndChildBrands,
      'Toys & Games': motherAndChildBrands,
      'Baby Care': motherAndChildBrands,
      'Maternity': motherAndChildBrands,
      'Strollers & Car Seats': motherAndChildBrands,
      'Feeding': motherAndChildBrands,
      'Safety': motherAndChildBrands,
    },
    'Home & Furniture': {
      'Furniture': homeAndFurnitureBrands,
      'Bedding & Bath': homeAndFurnitureBrands,
      'Home Decor': homeAndFurnitureBrands,
      'Kitchen & Dining': homeAndFurnitureBrands,
      'Bathroom': homeAndFurnitureBrands,
      'Lighting': homeAndFurnitureBrands,
      'Storage & Organization': homeAndFurnitureBrands,
      'Textiles': homeAndFurnitureBrands,
      'Appliances': homeAndFurnitureBrands,
    },
    'Cosmetics': {
      'Skincare': cosmeticsBrands,
      'Makeup': cosmeticsBrands,
      'Haircare': cosmeticsBrands,
      'Fragrances': cosmeticsBrands,
      'Personal Care': cosmeticsBrands,
      'Nail Care': cosmeticsBrands,
      'Body Care': cosmeticsBrands,
    },
    'Bags': {
      'Handbags': bagsBrands,
      'Backpacks': bagsBrands,
      'Tote Bags': bagsBrands,
      'Crossbody Bags': bagsBrands,
      'Clutches': bagsBrands,
      'Wallets': bagsBrands,
      'Luggage': bagsBrands,
      'Sport Bags': bagsBrands,
    },
    'Electronics': {
      'Smartphones & Accessories': electronicsBrands,
      'Laptops & Computers': electronicsBrands,
      'Tablets & E-Readers': electronicsBrands,
      'Audio & Headphones': electronicsBrands,
      'Cameras & Photography': electronicsBrands,
      'Televisions & Video': electronicsBrands,
      'Smart Home Devices': electronicsBrands,
      'Wearable Technology': electronicsBrands,
      'Gaming Consoles & Accessories': electronicsBrands,
      'Home Appliances': electronicsBrands,
      'Personal Care Appliances': electronicsBrands,
    },
    'Sports & Outdoor': {
      'Exercise & Fitness': sportsAndOutdoorBrands,
      'Camping & Hiking': sportsAndOutdoorBrands,
      'Cycling': sportsAndOutdoorBrands,
      'Team Sports': sportsAndOutdoorBrands,
      'Outdoor Recreation': sportsAndOutdoorBrands,
    },
    'Books, Stationery & Hobby': {
      'Books': booksStationeryHobbyBrands,
      'Stationery': booksStationeryHobbyBrands,
      'Art & Craft Supplies': booksStationeryHobbyBrands,
      'Hobby Kits': booksStationeryHobbyBrands,
      'Games & Puzzles': booksStationeryHobbyBrands,
      'Music & Instruments': booksStationeryHobbyBrands,
    },
};