// src/constants/sportsAndOutdoorBrands.js
export const sportsAndOutdoorBrands = [
   "Adidas",
  "ASICS",
  "Arc'teryx",
  "Athleta",
  "Beymen Club",
  "Bilcee",
  "Black Diamond",
  "Bonobos",
  "Columbia Sportswear",
  "Decathlon",
  "Everlane",
  "Exuma",
  "Fabletics",
  "Gymshark",
  "H&M",
  "Hoka One One",
  "Jack Wolfskin",
  "Koton",
  "LC Waikiki",
  "Lululemon",
  "Mammut",
  "Mavi",
  "Merrell",
  "Ministry of Supply",
  "Mizuno",
  "New Balance",
  "Nike",
  "On Running",
  "Outdoor Voices",
  "Patagonia",
  "Puma",
  "Rhone",
  "Salomon",
  "Sweaty Betty",
  "The North Face",
  "Umbro",
  "Under Armour",
  "Uniqlo",
  "Vakko",
  "Vuori",
  "Zara",
          ];
          