// src/constants/womenFashionBrands.js
export const womenFashionBrands = [
   "A.L.C.",
  "A.P.C.",
  "ASOS",
  "Abercrombie & Fitch",
  "Addax",
  "Adidas",
  "Aerie",
  "Akel",
  "Alexander McQueen",
  "AllSaints",
  "Alo Yoga",
  "American Eagle",
  "Anine Bing",
  "Anthropologie",
  "Armani",
  "Armine",
  "Asics",
  "Ay Yildiz",
  "Azzedine Alaïa",
  "Balenciaga",
  "Bally",
  "Banana Republic",
  "Baum und Pferdgarten",
  "Beach Bunny",
  "Bershka",
  "Beymen",
  "Biggdesign",
  "Bottega Veneta",
  "Boux Avenue",
  "Brunello Cucinelli",
  "Bueno Shoes",
  "Burberry",
  "By Malene Birger",
  "C&A",
  "Calvin Klein",
  "Celine",
  "Chanel",
  "Chloé",
  "Christian Dior",
  "Christian Louboutin",
  "Coach",
  "Collezione",
  "Columbia",
  "Commando",
  "Cos",
  "Cotton On",
  "Cuyana",
  "D&G (Dolce & Gabbana)",
  "Dainese",
  "Daks",
  "DeFacto",
  "Derimod",
  "Desa",
  "Diesel",
  "Dogo",
  "Eileen Fisher",
  "Elie Saab",
  "Emporio Armani",
  "Equipment",
  "Erdem",
  "Ermanno Scervino",
  "Esprit",
  "Everlane",
  "Fendi",
  "Figue",
  "Fiorucci",
  "Forever 21",
  "Frame",
  "Free People",
  "French Connection",
  "Ganni",
  "Gap",
  "Gestuz",
  "Ganni",
  "Givenchy",
  "Ganni",
  "Golden Goose",
  "Gucci",
  "H&M",
  "Hanro",
  "Harrods",
  "Helmut Lang",
  "Hermès",
  "Hotiç",
  "Hunkemöller",
  "Ipekyol",
  "Inci",
  "Intimissimi",
  "Isabel Marant",
  "J.Crew",
  "Jigsaw",
  "Jimmy Choo",
  "Jo Malone",
  "Jonathan Simkhai",
  "Joseph",
  "Kemal Tanca",
  "Kiğılı",
  "Khaite",
  "Koton",
  "L'Agent by Agent Provocateur",
  "LC Waikiki",
  "La Perla",
  "La Senza",
  "Lafuma",
  "Loro Piana",
  "Loro Piana",
  "Louis Vuitton",
  "Loveshackfancy",
  "Lululemon",
  "M&S (Marks & Spencer)",
  "MCM",
  "Maje",
  "Mango",
  "Marc Jacobs",
  "Massimo Dutti",
  "Mavi",
  "Max Mara",
  "Michael Kors",
  "Milly",
  "Miss Claire",
  "Missoni",
  "Modanisa",
  "Monamise",
  "Moncler",
  "Narkonteks",
  "Net-a-Porter",
  "New Balance",
  "Nike",
  "Nordstrom",
  "Nurteks",
  "Oxxo",
  "Paco Rabanne",
  "Patagonia",
  "Penti",
  "Philipp Plein",
  "Pinko",
  "Prada",
  "Primark",
  "Proenza Schouler",
  "Puma",
  "Rag & Bone",
  "Ralph Lauren",
  "Rebecca Minkoff",
  "Reformation",
  "Reiss",
  "Reiss",
  "Rick Owens",
  "River Island",
  "Rixo",
  "Sandro",
  "Sarar",
  "Sefamerve",
  "Seidensticker",
  "Self-Portrait",
  "Sisley",
  "Skechers",
  "Smythson",
  "Sonia Rykiel",
  "Stella McCartney",
  "Suwen",
  "Ted Baker",
  "The North Face",
  "Theory",
  "Tibi",
  "Tiffany & Co.",
  "Tod's",
  "Tommy Hilfiger",
  "Topshop",
  "Tory Burch",
  "Twist",
  "Under Armour",
  "Uniqlo",
  "Urban Outfitters",
  "Vakko",
  "Valentino",
  "Van Cleef & Arpels",
  "Vera Wang",
  "Versace",
  "Victoria Beckham",
  "Victoria's Secret",
  "Vilebrequin",
  "Vince",
  "Whistles",
  "YSL (Yves Saint Laurent)",
  "Zadig & Voltaire",
  "Zara",
  "Zimmermann",
  "Zuhre",
           ];
           